### ISSUE TITLE
vendor namespace

### ISSUE THREAD

**Issue by nadar** [baqianxin/luya-module-api#6]
I just saw that you are using `luya\` as your namepsace, you can do so if you like but commonly its better to use your vendor name as namespace like `oom` or `baqianxin` or whatever is your "name as developer".

So its clear its not an extension/module from luyadev its 3rd party application from `oom`/`baqianxin`.

**Comment by baqianxin** [comment]
thanks @nadar ,I just want to be close to Luya and I will modify the namespace
