### ISSUE TITLE
Using admin user

### ISSUE THREAD

**Issue by nadar** [baqianxin/luya-module-api#7]
Why not generate an access token for luya\admin\models\User luya\admin\models\ApiUser - so it would be an option to get an access token for an API user instead of having another table in between.

Admin user would be `Yii::$app->adminuser`

**Comment by baqianxin** [comment]
Yes, I was thinking about it this way, but I am afraid that the submitted code is not up to standard. I have created a new module for myself.

**Comment by baqianxin** [comment]
How do you think I added three fields (app_key，app_secret ,api_token ) to `admin_user` table?

**Comment by baqianxin** [comment]
![image](https://user-images.githubusercontent.com/6780391/39104900-1f07f046-46e5-11e8-91f3-4d1cc2fe7003.png)

**Comment by nadar** [comment]
You don't need to add those fields to to the admin_user table, just have your own junction table with the user id like

oom_admin_user_auth table:

user_id => admin_user.id
app_secret => ..
app_token => ..
created_at =>
etc.

This way you could have only 1 token for a given user as the token is stored in the admin_user table, but you can create new admin_users if needed.

**Comment by baqianxin** [comment]
OK, I will implement it this way. :grin:
